name: 🔧 Add a Developer Tool
description: Suggest a new developer tool to be added to the directory
title: "Add tool: [TOOL NAME]"
labels: ["enhancement", "tool-suggestion"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new tool! Please fill out the information below to help us add it to the directory.
        
        **Before submitting:**
        - Search existing tools to make sure it hasn't been added already
        - Make sure the tool is actively maintained and widely useful
        - Provide accurate and complete information

  - type: input
    id: tool-name
    attributes:
      label: Tool Name
      description: The official name of the tool
      placeholder: e.g., "Astro"
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: Official Website
      description: The main website or homepage
      placeholder: e.g., "https://astro.build"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which category best describes this tool?
      options:
        - AI
        - Backend
        - Build
        - CLI
        - Cloud
        - Collab
        - Data
        - DevEx
        - Frontend
        - Infra
        - Mobile
        - Observability
        - Performance
        - Security
        - Testing
        - UX
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: Tags
      description: Comma-separated list of relevant tags
      placeholder: e.g., "static-site-generator, javascript, typescript, performance"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Brief description of what the tool does (max 200 characters)
      placeholder: Describe the tool in 1-2 sentences
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this tool useful?
      description: Explain what problem it solves or what makes it special
      placeholder: Describe the key benefits and use cases
    validations:
      required: true

  - type: dropdown
    id: pricing
    attributes:
      label: Pricing Model
      description: How is this tool priced?
      options:
        - Free
        - Freemium
        - Paid
        - Open Source
    validations:
      required: true

  - type: textarea
    id: getting-started
    attributes:
      label: Getting Started
      description: Quick instructions for new users
      placeholder: How would someone get started with this tool?
    validations:
      required: true

  - type: input
    id: github
    attributes:
      label: GitHub Repository (Optional)
      description: Link to the GitHub repository if available
      placeholder: e.g., "https://github.com/withastro/astro"

  - type: input
    id: docs
    attributes:
      label: Documentation (Optional)
      description: Link to official documentation if different from website
      placeholder: e.g., "https://docs.astro.build"

  - type: checkboxes
    id: terms
    attributes:
      label: Verification
      description: Please confirm the following
      options:
        - label: I have searched existing tools and this is not a duplicate
          required: true
        - label: The tool is actively maintained and widely useful
          required: true
        - label: I have provided accurate information
          required: true
        - label: I understand this will be reviewed before being added
          required: true